[project]
name = "unix-tutorial"
version = "0.1.0"
description = "Tutoriel Unix"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-book>=1.0.3",
    "sphinxcontrib-mermaid>=1.0.0",
]
